services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chatApp
      - MONGO_INITDB_ROOT_PASSWORD=chatApp

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=chatApp
      - ME_CONFIG_MONGODB_ADMINPASSWORD=chatApp
      - ME_CONFIG_BASICAUTH_USERNAME=chatApp
      - ME_CONFIG_BASICAUTH_PASSWORD=chatApp
      #- ME_CONFIG_MONGODB_SERVER=localhost
      - ME_CONFIG_MONGODB_URL=mongodb://chatApp:chatApp@mongo:27017/
      #- ME_CONFIG_BASICAUTH=false

  app:
    build: .
    ports:
      - 8088:8088
    restart: always

volumes:
  mongo: {}
