services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chatApp
      - MONGO_INITDB_ROOT_PASSWORD=chatApp

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=chatApp
      - ME_CONFIG_MONGODB_ADMINPASSWORD=chatApp
      - ME_CONFIG_MONGODB_SERVER=localhost
      #- ME_CONFIG_MONGODB_URL=mongodb://mongo_db:27017
      - ME_CONFIG_BASICAUTH=false

volumes:
  mongo: {}
