services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mBHsgismjCvKQctIwgWYwxjApmGjbUsr

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mBHsgismjCvKQctIwgWYwxjApmGjbUsr
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mBHsgismjCvKQctIwgWYwxjApmGjbUsr
      #- ME_CONFIG_MONGODB_SERVER=localhost
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:mBHsgismjCvKQctIwgWYwxjApmGjbUsr@mongodb.railway.internal:27017
      #- ME_CONFIG_BASICAUTH=false

  app:
    build: .
    ports:
      - 8088:8088
    restart: always

volumes:
  mongo: {}
